name: Trigger Airflow DAG on Push

on:
  push:
    branches:
      - master

jobs:
  trigger-airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send cURL Request to Airflow DAG
        run: |
          curl -X POST "http://54.229.187.203:8080/api/v1/dags/convert_images_to_hdf5_ec2/dagRuns" \
          -H "Content-Type: application/json" \
          --user "admin:admin" \
          --data "{\"conf\":{\"dataset_name\": \"mnist\", \"binarization\": false}}"
